// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAs820VzFvja22UX4eAflaoLmNrQ9av80',
    appId: '1:990828640118:web:e3dcd86edd52e57d6e2c57',
    messagingSenderId: '990828640118',
    projectId: 'injustice-a1cca',
    authDomain: 'injustice-a1cca.firebaseapp.com',
    storageBucket: 'injustice-a1cca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEyJrw_vJQLWpYkVHrzEmmTN6QKjlrD9w',
    appId: '1:990828640118:android:d9343300eb771e576e2c57',
    messagingSenderId: '990828640118',
    projectId: 'injustice-a1cca',
    storageBucket: 'injustice-a1cca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB9R5h5PQrE5C3lZM7LkIbFfvYmwlGYnA',
    appId: '1:990828640118:ios:25118d193c98dd466e2c57',
    messagingSenderId: '990828640118',
    projectId: 'injustice-a1cca',
    storageBucket: 'injustice-a1cca.firebasestorage.app',
    iosBundleId: 'com.example.injusticeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB9R5h5PQrE5C3lZM7LkIbFfvYmwlGYnA',
    appId: '1:990828640118:ios:25118d193c98dd466e2c57',
    messagingSenderId: '990828640118',
    projectId: 'injustice-a1cca',
    storageBucket: 'injustice-a1cca.firebasestorage.app',
    iosBundleId: 'com.example.injusticeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAs820VzFvja22UX4eAflaoLmNrQ9av80',
    appId: '1:990828640118:web:9ab216e77e37c1e56e2c57',
    messagingSenderId: '990828640118',
    projectId: 'injustice-a1cca',
    authDomain: 'injustice-a1cca.firebaseapp.com',
    storageBucket: 'injustice-a1cca.firebasestorage.app',
  );
}
